AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
  DefaultFormatter: fuubar
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
#################### Layout ###############################

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

#################### Style ###############################

# Style/BracesAroundHashParameters:
#   EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ConditionalAssignment:
  Exclude:
    - app/views/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - app/models/**/*

#################### Metrics ###############################

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Layout/LineLength:
  Max: 150
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'spec/**/*.rb'
    - Gemfile
    - Rakefile
    - config/application.rb
    - config/environments/**/*
    - config/initializers/**/*

Metrics/ClassLength:
  Max: 200
#################### Bundler ###############################

Bundler/OrderedGems:
  Enabled: false
